### PR TITLE
Julia 1.0.4 is the latest LTS

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
@bswrundquist I saw you changed to 1.0.0, because of JDBC. v1.0.4 should work too; I'm not sure I'm doing this correctly, with the SHA(?), it needs changing? I realize I shouldn't probably have put in skip ci?

I also see you changed back to 1.1.1. Is JDBC/JavaCall/Spark not needed? I think the issue with them not working with 1.1+ is not resolved. It now has a 1.3 milestone, but that's scheduled for 10th August, and we may have to wait for 1.4 for JavaCall to work again?

If you do not go with v1.1.1 then the tag julia-v1.1.1 is misleading, and you may want to tag again.

**Comment by bswrundquist** [comment]
@PallHaraldsson Hey there!
Really appreciate you commenting on repo.
I've been a little fast and loose in how I've been creating builds and much of that is due to trying to use same image for Python, R, and Julia.
You are basically seeing (and pointed out correctly) the end of this repo since it's becoming too bloated and difficult to keep in order (14gb Docker image never goes over well with DevOps team...).
I'm planning on making a separate repo for each language and structuring it more clearly.
If you find any of this useful would love to hear your feedback.
I'm thinking for each something like (per language)

Base -> Numerical -> Useful -> [Kitchen Sink](https://knowyourphrase.com/everything-but-the-kitchen-sink) -> IDE (Jupyter for each language, remote VSCode, Rstudio)

Currently IDE is done first and am wondering if it should really be done last and use a build arg for whichever IDE is appropriate...Still pondering that one.
Also keep naming convention to describing types of packages instead of package names (scipy, etc).

Again, if this interests you perhaps I can throw up a project to create a clear roadmap and we can work together or at least make it easier for others to track progress.
And any feedback would be greatly appreciated.

Thanks!

**Comment by PallHaraldsson** [comment]
I don't really know much about your project. I just happened to be looking into the JavaCall.jl issue that affects e.g. JDBC.jl and Spark.jl. It you need either of those or other Java/Scala projects with Julia, then you were right to merge. At least for now, Julia-1.3.0-alpha even has a problem, and maybe 1.4 fixes it. I'm looking into an alternative solution to fix. I may let you know or if upstream fixes.

**Comment by bswrundquist** [comment]
Thanks for posting and feel free to let me know if you get it working, I'll be watching as well. The database I use requires JDBC connection so this is a blocker to make Julia an end-to-end solution for version > 1.0.4.

**Pull request merged**
